Python Program using Scikit-learn

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
# Sample words
words = np.array([
    ["I"],
    ["love"],
    ["NLP"],
    ["Python"]
])

In [4]:
# Create encoder
encoder = OneHotEncoder(sparse_output=False)


In [5]:
# Fit and transform
one_hot = encoder.fit_transform(words)


In [6]:
print(one_hot)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Python Program using TensorFlow/Keras

In [7]:
from tensorflow.keras.preprocessing.text import one_hot


In [8]:
text = [
    "I love NLP",
    "Python is awesome"
]

In [9]:
vocab_size = 20

encoded = [one_hot(sentence, vocab_size) for sentence in text]

print(encoded)

[[13, 18, 12], [1, 9, 3]]


In [10]:
#Python Program (Scikit-Learn) - Bag of words

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
documents = [
    "I love Python",
    "I love Machine Learning Machine Learning   & Machine Learning",
    "Python is easy"
]

In [16]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents) 

In [17]:
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nBag of Words Matrix:")
print(X.toarray())

Vocabulary:
['easy' 'is' 'learning' 'love' 'machine' 'python']

Bag of Words Matrix:
[[0 0 0 1 0 1]
 [0 0 3 1 3 0]
 [1 1 0 0 0 1]]


In [18]:
#Bag of Words (BoW) using NLTK

In [19]:
#Example 1: Simple Bag of Words using NLTK
#Step 1: Import Libraries
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

# Download required resources (run once)
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     c:\DS2026\Python\.venv\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [20]:
#Step 2: Input Sentence
text = "I love Python. I love Data Science."

In [22]:
#Step 3: Tokenize
tokens = word_tokenize(text.lower())

print(tokens)

#Output

#['i', 'love', 'python', '.', 'i', 'love', 'data', 'science', '.']

['i', 'love', 'python', '.', 'i', 'love', 'data', 'science', '.']


In [23]:
#Step 4: Remove Punctuation
words = [word for word in tokens if word.isalpha()]

print(words)

['i', 'love', 'python', 'i', 'love', 'data', 'science']


In [24]:
#Step 5: Count Words (Bag of Words)
bow = Counter(words)

print(bow)

Counter({'i': 2, 'love': 2, 'python': 1, 'data': 1, 'science': 1})


In [25]:
#Example 2: Bag of Words with Stop Word Removal
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter

# Download resources
nltk.download('punkt')
nltk.download('stopwords')

text = "I love Python. I love Data Science."

tokens = word_tokenize(text.lower())

# Keep only alphabetic words
words = [word for word in tokens if word.isalpha()]

# Remove stop words
stop_words = set(stopwords.words('english'))

filtered_words = [word for word in words if word not in stop_words]

bow = Counter(filtered_words)

print(bow)

[nltk_data] Downloading package punkt to
[nltk_data]     c:\DS2026\Python\.venv\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     c:\DS2026\Python\.venv\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


Counter({'love': 2, 'python': 1, 'data': 1, 'science': 1})


In [26]:
#Example 3: Multiple Documents (Manual BoW)
from nltk.tokenize import word_tokenize

documents = [
    "I love Python",
    "Python is easy",
    "I love Machine Learning"
]

# Build Vocabulary
vocabulary = sorted(set(
    word.lower()
    for doc in documents
    for word in word_tokenize(doc)
    if word.isalpha()
))

print("Vocabulary:")
print(vocabulary)

print("\nBag of Words Matrix:")

for doc in documents:
    words = word_tokenize(doc.lower())
    vector = [words.count(word) for word in vocabulary]
    print(vector)

Vocabulary:
['easy', 'i', 'is', 'learning', 'love', 'machine', 'python']

Bag of Words Matrix:
[0, 1, 0, 0, 1, 0, 1]
[1, 0, 1, 0, 0, 0, 1]
[0, 1, 0, 1, 1, 1, 0]


In [28]:
# N Grams

import nltk
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

# Download once
nltk.download('punkt')

text = "I love learning NLP"

tokens = word_tokenize(text)

# Bigrams
bigrams = list(ngrams(tokens, 2))

print(bigrams)

[('I', 'love'), ('love', 'learning'), ('learning', 'NLP')]


[nltk_data] Downloading package punkt to
[nltk_data]     c:\DS2026\Python\.venv\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [29]:
#Trigrams

trigrams = list(ngrams(tokens, 3))

print(trigrams)

[('I', 'love', 'learning'), ('love', 'learning', 'NLP')]


In [30]:
unigrams = list(ngrams(tokens, 1))

print(unigrams)

[('I',), ('love',), ('learning',), ('NLP',)]


In [31]:
# Bigrams
bigrams = list(ngrams(tokens, 2))

print(bigrams)

[('I', 'love'), ('love', 'learning'), ('learning', 'NLP')]


In [32]:
#Using Skilearn's CountVectorizer for N-Grams

from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love Python",
    "I love NLP"
]

vectorizer = CountVectorizer(ngram_range=(2,2))

X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())

print(X.toarray())

['love nlp' 'love python']
[[0 1]
 [1 0]]


TF-IDF (Term Frequency - Inverse Document Frequency)
TF-IDF is a text vectorization technique used in Natural Language Processing (NLP) to convert text into numerical vectors.

Unlike Bag of Words (BoW), which simply counts how often a word appears, TF-IDF assigns a weight to each word based on its importance in a document.

Idea: A word is important if it appears frequently in one document but rarely across all documents.

Why Do We Need TF-IDF?

Consider these three documents:

D1 = "I love Python"
D2 = "I love Machine Learning"
D3 = "I love Data Science"

Using Bag of Words, the word "love" gets a high count because it appears in every document.

But does "love" help distinguish one document from another?

No.

Instead, words like:

Python
Machine
Learning
Data
Science

are much more informative.

TF-IDF reduces the importance of common words and increases the importance of rare, distinguishing words.

Components of TF-IDF

TF-IDF consists of two parts:

1. Term Frequency (TF)

Term Frequency measures how often a word appears in a document.

Formula
TF=
Total number of words in the document
Number of times the term appears in the document
	​

Example

Document:

I love love Python

Total words = 4

Word	Count	TF
I	1	1/4 = 0.25
love	2	2/4 = 0.50
Python	1	1/4 = 0.25
2. Inverse Document Frequency (IDF)

IDF measures how rare or unique a word is across all documents.

Formula
IDF=log(
Number of Documents Containing the Word
Total Number of Documents
	​

)

Where:

N = Total number of documents
df = Number of documents containing the word
Example

Three documents:

D1 = I love Python
D2 = I love AI
D3 = I love Data
Word	Appears In	IDF
I	3 docs	Low
love	3 docs	Low
Python	1 doc	High
AI	1 doc	High
Data	1 doc	High

Common words get a small IDF.

Rare words get a large IDF.

TF-IDF Formula
TF-IDF=TF×IDF

A word receives a high score when:

It appears many times in one document (high TF)
It appears in very few documents (high IDF)
Step-by-Step Example

Documents:

D1 = "I love Python"
D2 = "I love AI"
D3 = "I love Data"

Vocabulary:

I
love
Python
AI
Data
TF

For D1:

Word	TF
I	1/3
love	1/3
Python	1/3
IDF
Word	Appears In	IDF
I	3	Low
love	3	Low
Python	1	High
AI	1	High
Data	1	High
TF-IDF
Word	TF	IDF	TF-IDF
I	0.33	Low	Small
love	0.33	Low	Small
Python	0.33	High	Large

Python receives the highest weight because it best distinguishes Document 1.

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love Python",
    "I love Machine Learning",
    "Python is easy"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(documents)



In [35]:
print(vectorizer.get_feature_names_out())


['easy' 'is' 'learning' 'love' 'machine' 'python']


In [36]:

print(X.toarray())

[[0.         0.         0.         0.70710678 0.         0.70710678]
 [0.         0.         0.62276601 0.4736296  0.62276601 0.        ]
 [0.62276601 0.62276601 0.         0.         0.         0.4736296 ]]
