In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2923, 5223, 5543, 6184],
 [2923, 5223, 5543, 4415],
 [2923, 3559, 5543, 5524],
 [5999, 8647, 6347, 6066, 4753],
 [5999, 8647, 6347, 6066, 1771],
 [143, 2923, 6009, 5543, 4636],
 [5283, 404, 7621, 6066]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2923 5223 5543 6184]
 [   0    0    0    0 2923 5223 5543 4415]
 [   0    0    0    0 2923 3559 5543 5524]
 [   0    0    0 5999 8647 6347 6066 4753]
 [   0    0    0 5999 8647 6347 6066 1771]
 [   0    0    0  143 2923 6009 5543 4636]
 [   0    0    0    0 5283  404 7621 6066]]


In [8]:
## feature representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\DS2026\Python\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[ 0.02875434, -0.00181923,  0.03620588, -0.03414582,
          0.02968905,  0.00384312,  0.00488567,  0.01382228,
         -0.02402176, -0.03070587],
        [ 0.02875434, -0.00181923,  0.03620588, -0.03414582,
          0.02968905,  0.00384312,  0.00488567,  0.01382228,
         -0.02402176, -0.03070587],
        [ 0.02875434, -0.00181923,  0.03620588, -0.03414582,
          0.02968905,  0.00384312,  0.00488567,  0.01382228,
         -0.02402176, -0.03070587],
        [ 0.02875434, -0.00181923,  0.03620588, -0.03414582,
          0.02968905,  0.00384312,  0.00488567,  0.01382228,
         -0.02402176, -0.03070587],
        [-0.01559011, -0.03203286, -0.01277126, -0.02319683,
          0.04046852, -0.04061832,  0.03663504, -0.048738  ,
          0.03850475,  0.04420102],
        [ 0.0278896 , -0.00189565, -0.00418425,  0.02141057,
         -0.03352517, -0.0440243 , -0.00332515, -0.03216453,
         -0.0236549 ,  0.00887927],
        [-0.00549643,  0.02147895,  0.03373699,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2923, 5223, 5543, 6184], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>