In [2]:
!pip install numpy

  Using cached numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)


In [3]:
import numpy as np  


In [4]:
np.array([1, 2, 3])
np.array([[1, 2, 3], [4, 5, 6]])

print(np.array([1, 2, 3]))
print(np.array([[1, 2, 3], [4, 5, 6]])) 

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Array Attributes   

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)   # Dimensions
print(arr.shape)  # (rows, cols)
print(arr.size)   # Total elements
print(arr.dtype)  # Data type


2
(2, 3)
6
int64


In [9]:
#CReateing special arrays

print(np.zeros((2,3)) )  
  # All zeros
print(np.ones((3,3)) )  
   # All ones
print(np.eye(3) )      
    # Identity matrix
print(np.arange(0,10,2) ) 
# Range
print(np.linspace(0,1,5) )
 # Equal spacing
print(np.random.rand(2,2) )
# Random values

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.47847613 0.75777449]
 [0.95052495 0.19128417]]


In [10]:
#Indexign & Slicing

arr = np.array([10, 20, 30, 40])

print(arr[0])      # 10
print(arr[1:3])    # [20,30]

10
[20 30]


In [11]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0,1])    # 2
print(arr[:,1])    # column
print(arr[1,:])    # row

2
[2 5]
[4 5 6]


In [12]:
#Array Operations

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [13]:
#broadcasting

a = np.array([1,2,3])
b = 2

print(a + b)  # [3,4,5]

[3 4 5]


In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr + np.array([10,20,30]))

[[11 22 33]
 [14 25 36]]


In [17]:
#Mathematical Functions

arr = np.array([1,2,3,4])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.sqrt(arr))
print(np.log(arr))



10
2.5
4
1
1.118033988749895
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]


In [19]:
#Reshaping Arrays   

arr = np.arange(6)

print(arr)

print(arr.reshape(2,3))
print(arr.reshape(3,2))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [20]:
#Falttening Arrays  
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [21]:
#Stacking Arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.stack((a, b), axis=0)
print(res)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [23]:
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [24]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [27]:
a = np.array([1,2,3])
b = a            # reference
c = a.copy()     # copy

a[0] = 10

print(b)  # changed
print(c)  # unchanged
print(a)  # changed
print

[10  2  3]
[1 2 3]
[10  2  3]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [31]:
#Random Modules

print(np.random.rand(5))       # 0-1
print(np.random.randn(3))      # normal dist
print(np.random.randint(1,100,5))

[0.87132373 0.6359765  0.00391435 0.95609562 0.88032799]
[-0.23782285  0.13843056 -0.54505032]
[50 73  5 88 16]


In [32]:
#Python Lists vs NumPy Arrays

import time

# Python list
lst = list(range(1000000))
start = time.time()
[x*2 for x in lst]
print(time.time()-start)

# NumPy
arr = np.arange(1000000)
start = time.time()
arr * 2
print(time.time()-start)

0.15047144889831543
0.005536556243896484
